/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 6
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_release_statement_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_DOT = 4,
  anon_sym_EQ = 5,
  anon_sym_COMMA = 6,
  aux_sym_export_header_identifier_token1 = 7,
  anon_sym_DOLLARPBExportComments_DOLLAR = 8,
  aux_sym_export_header_comments_token1 = 9,
  anon_sym_srd = 10,
  sym_integer_literal = 11,
  sym_decimal_literal = 12,
  sym_real_literal = 13,
  sym_date_literal = 14,
  sym_time_literal = 15,
  aux_sym_string_literal_token1 = 16,
  aux_sym_string_literal_token2 = 17,
  aux_sym_boolean_literal_token1 = 18,
  aux_sym_boolean_literal_token2 = 19,
  anon_sym_SLASH_SLASH = 20,
  aux_sym_line_comment_token1 = 21,
  sym_block_comment = 22,
  sym_open_parenthesis = 23,
  sym_close_parenthesis = 24,
  sym_single_quote = 25,
  sym_double_quote = 26,
  sym_source_file = 27,
  sym_datawindow_file = 28,
  sym_release_statement = 29,
  sym_datawindow_statement = 30,
  sym_datawindow_method_invocation = 31,
  sym_datawindow_field_access = 32,
  sym_datawindow_property_list = 33,
  sym_datawindow_property_assignment = 34,
  sym_datawindow_map_list = 35,
  sym_export_header = 36,
  sym_export_header_identifier = 37,
  sym_export_header_identifier_content = 38,
  sym_export_header_comments = 39,
  sym_file_extension = 40,
  sym__literal = 41,
  sym_string_literal = 42,
  sym_boolean_literal = 43,
  sym_line_comment = 44,
  aux_sym_datawindow_file_repeat1 = 45,
  aux_sym_datawindow_property_list_repeat1 = 46,
  aux_sym_datawindow_property_assignment_repeat1 = 47,
  aux_sym_datawindow_map_list_repeat1 = 48,
  aux_sym_string_literal_repeat1 = 49,
  aux_sym_string_literal_repeat2 = 50,
  alias_sym_datawindow_definition_method = 51,
  alias_sym_field = 52,
  alias_sym_file_name = 53,
  alias_sym_release_version = 54,
  alias_sym_string_content = 55,
  alias_sym_value = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "method",
  [aux_sym_release_statement_token1] = "release",
  [anon_sym_SEMI] = ";",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [aux_sym_export_header_identifier_token1] = "export_header_identifier_text",
  [anon_sym_DOLLARPBExportComments_DOLLAR] = "export_header_comments_text",
  [aux_sym_export_header_comments_token1] = "export_header_comments_content",
  [anon_sym_srd] = "dataobject_file_extension",
  [sym_integer_literal] = "integer_literal",
  [sym_decimal_literal] = "decimal_literal",
  [sym_real_literal] = "real_literal",
  [sym_date_literal] = "date_literal",
  [sym_time_literal] = "time_literal",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [aux_sym_boolean_literal_token1] = "true",
  [aux_sym_boolean_literal_token2] = "false",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [sym_block_comment] = "block_comment",
  [sym_open_parenthesis] = "open_parenthesis",
  [sym_close_parenthesis] = "close_parenthesis",
  [sym_single_quote] = "single_quote",
  [sym_double_quote] = "double_quote",
  [sym_source_file] = "source_file",
  [sym_datawindow_file] = "datawindow_file",
  [sym_release_statement] = "release_statement",
  [sym_datawindow_statement] = "datawindow_statement",
  [sym_datawindow_method_invocation] = "object",
  [sym_datawindow_field_access] = "property",
  [sym_datawindow_property_list] = "datawindow_property_list",
  [sym_datawindow_property_assignment] = "datawindow_property_assignment",
  [sym_datawindow_map_list] = "datawindow_map_list",
  [sym_export_header] = "export_header",
  [sym_export_header_identifier] = "export_header_identifier",
  [sym_export_header_identifier_content] = "export_header_identifier_content",
  [sym_export_header_comments] = "export_header_comments",
  [sym_file_extension] = "file_extension",
  [sym__literal] = "_literal",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_line_comment] = "line_comment",
  [aux_sym_datawindow_file_repeat1] = "datawindow_file_repeat1",
  [aux_sym_datawindow_property_list_repeat1] = "datawindow_property_list_repeat1",
  [aux_sym_datawindow_property_assignment_repeat1] = "datawindow_property_assignment_repeat1",
  [aux_sym_datawindow_map_list_repeat1] = "datawindow_map_list_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_string_literal_repeat2] = "string_literal_repeat2",
  [alias_sym_datawindow_definition_method] = "datawindow_definition_method",
  [alias_sym_field] = "field",
  [alias_sym_file_name] = "file_name",
  [alias_sym_release_version] = "release_version",
  [alias_sym_string_content] = "string_content",
  [alias_sym_value] = "value",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_release_statement_token1] = aux_sym_release_statement_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_export_header_identifier_token1] = aux_sym_export_header_identifier_token1,
  [anon_sym_DOLLARPBExportComments_DOLLAR] = anon_sym_DOLLARPBExportComments_DOLLAR,
  [aux_sym_export_header_comments_token1] = aux_sym_export_header_comments_token1,
  [anon_sym_srd] = anon_sym_srd,
  [sym_integer_literal] = sym_integer_literal,
  [sym_decimal_literal] = sym_decimal_literal,
  [sym_real_literal] = sym_real_literal,
  [sym_date_literal] = sym_date_literal,
  [sym_time_literal] = sym_time_literal,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [aux_sym_boolean_literal_token1] = aux_sym_boolean_literal_token1,
  [aux_sym_boolean_literal_token2] = aux_sym_boolean_literal_token2,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [sym_block_comment] = sym_block_comment,
  [sym_open_parenthesis] = sym_open_parenthesis,
  [sym_close_parenthesis] = sym_close_parenthesis,
  [sym_single_quote] = sym_single_quote,
  [sym_double_quote] = sym_double_quote,
  [sym_source_file] = sym_source_file,
  [sym_datawindow_file] = sym_datawindow_file,
  [sym_release_statement] = sym_release_statement,
  [sym_datawindow_statement] = sym_datawindow_statement,
  [sym_datawindow_method_invocation] = sym_datawindow_method_invocation,
  [sym_datawindow_field_access] = sym_datawindow_field_access,
  [sym_datawindow_property_list] = sym_datawindow_property_list,
  [sym_datawindow_property_assignment] = sym_datawindow_property_assignment,
  [sym_datawindow_map_list] = sym_datawindow_map_list,
  [sym_export_header] = sym_export_header,
  [sym_export_header_identifier] = sym_export_header_identifier,
  [sym_export_header_identifier_content] = sym_export_header_identifier_content,
  [sym_export_header_comments] = sym_export_header_comments,
  [sym_file_extension] = sym_file_extension,
  [sym__literal] = sym__literal,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_line_comment] = sym_line_comment,
  [aux_sym_datawindow_file_repeat1] = aux_sym_datawindow_file_repeat1,
  [aux_sym_datawindow_property_list_repeat1] = aux_sym_datawindow_property_list_repeat1,
  [aux_sym_datawindow_property_assignment_repeat1] = aux_sym_datawindow_property_assignment_repeat1,
  [aux_sym_datawindow_map_list_repeat1] = aux_sym_datawindow_map_list_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_string_literal_repeat2] = aux_sym_string_literal_repeat2,
  [alias_sym_datawindow_definition_method] = alias_sym_datawindow_definition_method,
  [alias_sym_field] = alias_sym_field,
  [alias_sym_file_name] = alias_sym_file_name,
  [alias_sym_release_version] = alias_sym_release_version,
  [alias_sym_string_content] = alias_sym_string_content,
  [alias_sym_value] = alias_sym_value,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_release_statement_token1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_export_header_identifier_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLARPBExportComments_DOLLAR] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_export_header_comments_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_srd] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_real_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_date_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_time_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_boolean_literal_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_boolean_literal_token2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_open_parenthesis] = {
    .visible = true,
    .named = true,
  },
  [sym_close_parenthesis] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_file] = {
    .visible = true,
    .named = true,
  },
  [sym_release_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_method_invocation] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_field_access] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_property_list] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_property_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_map_list] = {
    .visible = true,
    .named = true,
  },
  [sym_export_header] = {
    .visible = true,
    .named = true,
  },
  [sym_export_header_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_export_header_identifier_content] = {
    .visible = true,
    .named = true,
  },
  [sym_export_header_comments] = {
    .visible = true,
    .named = true,
  },
  [sym_file_extension] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_datawindow_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_datawindow_property_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_datawindow_property_assignment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_datawindow_map_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat2] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_datawindow_definition_method] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_field] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_file_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_release_version] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_value] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_datawindow_definition_method,
  },
  [2] = {
    [1] = alias_sym_release_version,
  },
  [3] = {
    [0] = sym_datawindow_method_invocation,
    [2] = alias_sym_field,
  },
  [4] = {
    [0] = alias_sym_file_name,
  },
  [5] = {
    [0] = sym_datawindow_method_invocation,
    [1] = sym_datawindow_method_invocation,
  },
  [6] = {
    [0] = sym_datawindow_field_access,
    [2] = alias_sym_value,
  },
  [7] = {
    [0] = sym_datawindow_field_access,
  },
  [8] = {
    [1] = alias_sym_string_content,
  },
  [9] = {
    [1] = alias_sym_value,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_datawindow_method_invocation, 2,
    sym_datawindow_method_invocation,
    alias_sym_datawindow_definition_method,
  sym_datawindow_field_access, 2,
    sym_datawindow_field_access,
    sym_datawindow_method_invocation,
  sym__literal, 2,
    sym__literal,
    alias_sym_value,
  aux_sym_string_literal_repeat1, 2,
    aux_sym_string_literal_repeat1,
    alias_sym_string_content,
  aux_sym_string_literal_repeat2, 2,
    aux_sym_string_literal_repeat2,
    alias_sym_string_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(67);
      ADVANCE_MAP(
        '"', 142,
        '$', 18,
        '\'', 141,
        '(', 139,
        ')', 140,
        ',', 72,
        '.', 70,
        '/', 6,
        '2', 107,
        ';', 68,
        '=', 71,
        'H', 83,
        'F', 98,
        'f', 98,
        'T', 101,
        't', 101,
        '0', 108,
        '1', 108,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(111);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 142,
        '\'', 141,
        '.', 53,
        '/', 6,
        '2', 107,
        'F', 43,
        'f', 43,
        'T', 48,
        't', 48,
        '0', 108,
        '1', 108,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(111);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(142);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == '~') ADVANCE(126);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(125);
      if (lookahead != 0) ADVANCE(125);
      END_STATE();
    case 3:
      if (lookahead == '$') ADVANCE(73);
      END_STATE();
    case 4:
      if (lookahead == '$') ADVANCE(75);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(141);
      if (lookahead == '/') ADVANCE(127);
      if (lookahead == '\\') ADVANCE(63);
      if (lookahead == '~') ADVANCE(128);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(127);
      if (lookahead != 0) ADVANCE(127);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(131);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(138);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(62);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(60);
      if (lookahead == '/') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(52);
      END_STATE();
    case 12:
      if (lookahead == 'B') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'B') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'C') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'C') ADVANCE(29);
      if (lookahead == 'H') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(40);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(41);
      END_STATE();
    case 18:
      if (lookahead == 'P') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 'P') ADVANCE(13);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(30);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(3);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(4);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 40:
      if (lookahead == 'x') ADVANCE(31);
      END_STATE();
    case 41:
      if (lookahead == 'x') ADVANCE(32);
      END_STATE();
    case 42:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 43:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(47);
      END_STATE();
    case 44:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 45:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(129);
      END_STATE();
    case 46:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(130);
      END_STATE();
    case 47:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 48:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 49:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(46);
      END_STATE();
    case 50:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(55);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(57);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      END_STATE();
    case 59:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 62:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 63:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(127);
      END_STATE();
    case 64:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(125);
      END_STATE();
    case 65:
      if (eof) ADVANCE(67);
      ADVANCE_MAP(
        '"', 142,
        '$', 19,
        '\'', 141,
        '(', 139,
        ')', 140,
        ',', 72,
        '.', 53,
        '/', 6,
        '2', 107,
        'F', 98,
        'f', 98,
        'T', 101,
        't', 101,
        '0', 108,
        '1', 108,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(65);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(111);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 66:
      if (eof) ADVANCE(67);
      if (lookahead == '(') ADVANCE(139);
      if (lookahead == '.') ADVANCE(69);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_export_header_identifier_token1);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_export_header_identifier_token1);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_DOLLARPBExportComments_DOLLAR);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_export_header_comments_token1);
      if (lookahead == '*') ADVANCE(78);
      if (lookahead == '/') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(80);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_export_header_comments_token1);
      if (lookahead == '*') ADVANCE(77);
      if (lookahead == '/') ADVANCE(80);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(8);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_export_header_comments_token1);
      if (lookahead == '*') ADVANCE(77);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(8);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_export_header_comments_token1);
      if (lookahead == '/') ADVANCE(76);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_export_header_comments_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$') ADVANCE(87);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$') ADVANCE(74);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(81);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'B') ADVANCE(85);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(97);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'H') ADVANCE(90);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P') ADVANCE(84);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(89);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(91);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(88);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(95);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(94);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(92);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(96);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(82);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(86);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(93);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(100);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(104);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(102);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(103);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(99);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(99);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '-') ADVANCE(61);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == ':') ADVANCE(51);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(109);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(106);
      if (('4' <= lookahead && lookahead <= '9')) ADVANCE(110);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(109);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_decimal_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_decimal_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_real_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_date_literal);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_time_literal);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_time_literal);
      if (lookahead == '.') ADVANCE(58);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_time_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_time_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_time_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_time_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_time_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '"') ADVANCE(125);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead == '\'') ADVANCE(127);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_boolean_literal_token1);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_boolean_literal_token2);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(80);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(135);
      if (lookahead == '/') ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(137);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(134);
      if (lookahead == '/') ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(135);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(135);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '/') ADVANCE(133);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(136);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(137);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(137);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_open_parenthesis);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_close_parenthesis);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_single_quote);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_double_quote);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 's') ADVANCE(1);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'd') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_srd);
      END_STATE();
    case 6:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_release_statement_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 65},
  [3] = {.lex_state = 65},
  [4] = {.lex_state = 65},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 65},
  [7] = {.lex_state = 65},
  [8] = {.lex_state = 65},
  [9] = {.lex_state = 65},
  [10] = {.lex_state = 65},
  [11] = {.lex_state = 65},
  [12] = {.lex_state = 65},
  [13] = {.lex_state = 65},
  [14] = {.lex_state = 66},
  [15] = {.lex_state = 66},
  [16] = {.lex_state = 65},
  [17] = {.lex_state = 66},
  [18] = {.lex_state = 66},
  [19] = {.lex_state = 66},
  [20] = {.lex_state = 65},
  [21] = {.lex_state = 66},
  [22] = {.lex_state = 65},
  [23] = {.lex_state = 65},
  [24] = {.lex_state = 65},
  [25] = {.lex_state = 66},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 65},
  [29] = {.lex_state = 65},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 65},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 65},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 65},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 65},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 65},
  [48] = {.lex_state = 66},
  [49] = {.lex_state = 65},
  [50] = {.lex_state = 65},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 65},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 65},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 65},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 65},
  [60] = {.lex_state = 10},
  [61] = {.lex_state = 66},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 65},
  [64] = {.lex_state = 65},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 65},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 66},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 66},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 65},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 136},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 79},
  [83] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_release_statement_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_export_header_identifier_token1] = ACTIONS(1),
    [anon_sym_DOLLARPBExportComments_DOLLAR] = ACTIONS(1),
    [anon_sym_srd] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_decimal_literal] = ACTIONS(1),
    [sym_real_literal] = ACTIONS(1),
    [sym_date_literal] = ACTIONS(1),
    [sym_time_literal] = ACTIONS(1),
    [aux_sym_boolean_literal_token1] = ACTIONS(1),
    [aux_sym_boolean_literal_token2] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [sym_open_parenthesis] = ACTIONS(1),
    [sym_close_parenthesis] = ACTIONS(1),
    [sym_single_quote] = ACTIONS(1),
    [sym_double_quote] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(75),
    [sym_datawindow_file] = STATE(76),
    [sym_release_statement] = STATE(28),
    [sym_datawindow_statement] = STATE(28),
    [sym_datawindow_method_invocation] = STATE(17),
    [sym_datawindow_field_access] = STATE(70),
    [sym_export_header] = STATE(8),
    [sym_export_header_identifier] = STATE(16),
    [sym_line_comment] = STATE(1),
    [aux_sym_datawindow_file_repeat1] = STATE(9),
    [sym_identifier] = ACTIONS(7),
    [aux_sym_release_statement_token1] = ACTIONS(9),
    [aux_sym_export_header_identifier_token1] = ACTIONS(11),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_open_parenthesis,
    ACTIONS(23), 1,
      sym_single_quote,
    ACTIONS(25), 1,
      sym_double_quote,
    STATE(2), 1,
      sym_line_comment,
    STATE(47), 1,
      sym__literal,
    ACTIONS(15), 2,
      sym_integer_literal,
      sym_decimal_literal,
    ACTIONS(19), 2,
      aux_sym_boolean_literal_token1,
      aux_sym_boolean_literal_token2,
    STATE(23), 2,
      sym_string_literal,
      sym_boolean_literal,
    ACTIONS(17), 3,
      sym_real_literal,
      sym_date_literal,
      sym_time_literal,
  [42] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(23), 1,
      sym_single_quote,
    ACTIONS(25), 1,
      sym_double_quote,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_close_parenthesis,
    STATE(3), 1,
      sym_line_comment,
    STATE(35), 1,
      sym__literal,
    ACTIONS(15), 2,
      sym_integer_literal,
      sym_decimal_literal,
    ACTIONS(19), 2,
      aux_sym_boolean_literal_token1,
      aux_sym_boolean_literal_token2,
    STATE(23), 2,
      sym_string_literal,
      sym_boolean_literal,
    ACTIONS(17), 3,
      sym_real_literal,
      sym_date_literal,
      sym_time_literal,
  [84] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(23), 1,
      sym_single_quote,
    ACTIONS(25), 1,
      sym_double_quote,
    ACTIONS(31), 1,
      sym_identifier,
    STATE(4), 1,
      sym_line_comment,
    STATE(66), 1,
      sym__literal,
    ACTIONS(15), 2,
      sym_integer_literal,
      sym_decimal_literal,
    ACTIONS(19), 2,
      aux_sym_boolean_literal_token1,
      aux_sym_boolean_literal_token2,
    STATE(23), 2,
      sym_string_literal,
      sym_boolean_literal,
    ACTIONS(17), 3,
      sym_real_literal,
      sym_date_literal,
      sym_time_literal,
  [123] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(23), 1,
      sym_single_quote,
    ACTIONS(25), 1,
      sym_double_quote,
    STATE(5), 1,
      sym_line_comment,
    STATE(73), 1,
      sym__literal,
    ACTIONS(15), 2,
      sym_integer_literal,
      sym_decimal_literal,
    ACTIONS(33), 2,
      aux_sym_boolean_literal_token1,
      aux_sym_boolean_literal_token2,
    STATE(23), 2,
      sym_string_literal,
      sym_boolean_literal,
    ACTIONS(17), 3,
      sym_real_literal,
      sym_date_literal,
      sym_time_literal,
  [159] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_open_parenthesis,
    ACTIONS(39), 1,
      sym_close_parenthesis,
    STATE(6), 1,
      sym_line_comment,
    STATE(13), 1,
      aux_sym_datawindow_property_list_repeat1,
    STATE(30), 1,
      sym_datawindow_map_list,
    STATE(48), 1,
      sym_datawindow_field_access,
    STATE(50), 1,
      sym_datawindow_property_assignment,
    STATE(70), 1,
      sym_datawindow_method_invocation,
    STATE(78), 1,
      sym_datawindow_property_list,
  [196] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(46), 1,
      aux_sym_release_statement_token1,
    STATE(17), 1,
      sym_datawindow_method_invocation,
    STATE(70), 1,
      sym_datawindow_field_access,
    STATE(7), 2,
      sym_line_comment,
      aux_sym_datawindow_file_repeat1,
    STATE(28), 2,
      sym_release_statement,
      sym_datawindow_statement,
  [226] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      aux_sym_release_statement_token1,
    STATE(8), 1,
      sym_line_comment,
    STATE(9), 1,
      aux_sym_datawindow_file_repeat1,
    STATE(17), 1,
      sym_datawindow_method_invocation,
    STATE(70), 1,
      sym_datawindow_field_access,
    STATE(79), 1,
      sym_datawindow_file,
    STATE(28), 2,
      sym_release_statement,
      sym_datawindow_statement,
  [258] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      aux_sym_release_statement_token1,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_datawindow_file_repeat1,
    STATE(9), 1,
      sym_line_comment,
    STATE(17), 1,
      sym_datawindow_method_invocation,
    STATE(70), 1,
      sym_datawindow_field_access,
    STATE(28), 2,
      sym_release_statement,
      sym_datawindow_statement,
  [290] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(51), 1,
      sym_close_parenthesis,
    STATE(10), 1,
      sym_line_comment,
    STATE(13), 1,
      aux_sym_datawindow_property_list_repeat1,
    STATE(48), 1,
      sym_datawindow_field_access,
    STATE(50), 1,
      sym_datawindow_property_assignment,
    STATE(70), 1,
      sym_datawindow_method_invocation,
    STATE(81), 1,
      sym_datawindow_property_list,
  [321] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(53), 1,
      sym_close_parenthesis,
    STATE(11), 1,
      sym_line_comment,
    STATE(13), 1,
      aux_sym_datawindow_property_list_repeat1,
    STATE(48), 1,
      sym_datawindow_field_access,
    STATE(50), 1,
      sym_datawindow_property_assignment,
    STATE(70), 1,
      sym_datawindow_method_invocation,
    STATE(71), 1,
      sym_datawindow_property_list,
  [352] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_close_parenthesis,
    STATE(48), 1,
      sym_datawindow_field_access,
    STATE(50), 1,
      sym_datawindow_property_assignment,
    STATE(70), 1,
      sym_datawindow_method_invocation,
    STATE(12), 2,
      sym_line_comment,
      aux_sym_datawindow_property_list_repeat1,
  [378] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(60), 1,
      sym_close_parenthesis,
    STATE(12), 1,
      aux_sym_datawindow_property_list_repeat1,
    STATE(13), 1,
      sym_line_comment,
    STATE(48), 1,
      sym_datawindow_field_access,
    STATE(50), 1,
      sym_datawindow_property_assignment,
    STATE(70), 1,
      sym_datawindow_method_invocation,
  [406] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(14), 1,
      sym_line_comment,
    ACTIONS(62), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
    ACTIONS(64), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [424] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(15), 1,
      sym_line_comment,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
    ACTIONS(68), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [442] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(72), 1,
      anon_sym_DOLLARPBExportComments_DOLLAR,
    STATE(16), 1,
      sym_line_comment,
    STATE(59), 1,
      sym_export_header_comments,
    ACTIONS(70), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [462] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 1,
      anon_sym_DOT,
    STATE(17), 1,
      sym_line_comment,
    ACTIONS(76), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [482] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(18), 1,
      sym_line_comment,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
    ACTIONS(82), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [500] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(19), 1,
      sym_line_comment,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
    ACTIONS(86), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [518] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_line_comment,
    ACTIONS(90), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [535] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(94), 1,
      sym_open_parenthesis,
    STATE(21), 1,
      sym_line_comment,
    ACTIONS(92), 2,
      anon_sym_DOT,
      anon_sym_EQ,
  [552] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(98), 1,
      sym_open_parenthesis,
    STATE(22), 1,
      sym_line_comment,
    ACTIONS(96), 2,
      sym_identifier,
      sym_close_parenthesis,
  [569] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(23), 1,
      sym_line_comment,
    ACTIONS(100), 3,
      anon_sym_COMMA,
      sym_identifier,
      sym_close_parenthesis,
  [584] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(24), 1,
      sym_line_comment,
    ACTIONS(102), 3,
      anon_sym_COMMA,
      sym_identifier,
      sym_close_parenthesis,
  [599] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(78), 1,
      anon_sym_DOT,
    ACTIONS(104), 1,
      anon_sym_EQ,
    ACTIONS(106), 1,
      sym_open_parenthesis,
    STATE(25), 1,
      sym_line_comment,
  [618] = 6,
    ACTIONS(108), 1,
      aux_sym_string_literal_token2,
    ACTIONS(110), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      sym_block_comment,
    ACTIONS(114), 1,
      sym_single_quote,
    STATE(26), 1,
      sym_line_comment,
    STATE(32), 1,
      aux_sym_string_literal_repeat2,
  [637] = 6,
    ACTIONS(110), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      sym_block_comment,
    ACTIONS(114), 1,
      sym_double_quote,
    ACTIONS(116), 1,
      aux_sym_string_literal_token1,
    STATE(27), 1,
      sym_line_comment,
    STATE(33), 1,
      aux_sym_string_literal_repeat1,
  [656] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      sym_line_comment,
    ACTIONS(120), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [673] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(124), 1,
      anon_sym_DOLLARPBExportComments_DOLLAR,
    STATE(29), 1,
      sym_line_comment,
    ACTIONS(122), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [690] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(126), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      sym_close_parenthesis,
    STATE(30), 1,
      sym_line_comment,
    STATE(36), 1,
      aux_sym_datawindow_property_assignment_repeat1,
  [709] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(31), 1,
      sym_line_comment,
    ACTIONS(130), 3,
      anon_sym_COMMA,
      sym_identifier,
      sym_close_parenthesis,
  [724] = 6,
    ACTIONS(108), 1,
      aux_sym_string_literal_token2,
    ACTIONS(110), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      sym_block_comment,
    ACTIONS(132), 1,
      sym_single_quote,
    STATE(32), 1,
      sym_line_comment,
    STATE(38), 1,
      aux_sym_string_literal_repeat2,
  [743] = 6,
    ACTIONS(110), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      sym_block_comment,
    ACTIONS(116), 1,
      aux_sym_string_literal_token1,
    ACTIONS(132), 1,
      sym_double_quote,
    STATE(33), 1,
      sym_line_comment,
    STATE(39), 1,
      aux_sym_string_literal_repeat1,
  [762] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      sym_close_parenthesis,
    STATE(34), 1,
      sym_line_comment,
    STATE(41), 1,
      aux_sym_datawindow_map_list_repeat1,
  [781] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      sym_close_parenthesis,
    STATE(35), 1,
      sym_line_comment,
    STATE(43), 1,
      aux_sym_datawindow_map_list_repeat1,
  [800] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(126), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      sym_close_parenthesis,
    STATE(36), 1,
      sym_line_comment,
    STATE(44), 1,
      aux_sym_datawindow_property_assignment_repeat1,
  [819] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(37), 1,
      sym_line_comment,
    ACTIONS(142), 3,
      anon_sym_COMMA,
      sym_identifier,
      sym_close_parenthesis,
  [834] = 5,
    ACTIONS(110), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      sym_block_comment,
    ACTIONS(144), 1,
      aux_sym_string_literal_token2,
    ACTIONS(147), 1,
      sym_single_quote,
    STATE(38), 2,
      sym_line_comment,
      aux_sym_string_literal_repeat2,
  [851] = 5,
    ACTIONS(110), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      sym_block_comment,
    ACTIONS(149), 1,
      aux_sym_string_literal_token1,
    ACTIONS(152), 1,
      sym_double_quote,
    STATE(39), 2,
      sym_line_comment,
      aux_sym_string_literal_repeat1,
  [868] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(156), 1,
      anon_sym_DOLLARPBExportComments_DOLLAR,
    STATE(40), 1,
      sym_line_comment,
    ACTIONS(154), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [885] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      sym_close_parenthesis,
    STATE(41), 1,
      sym_line_comment,
    STATE(45), 1,
      aux_sym_datawindow_map_list_repeat1,
  [904] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(162), 1,
      anon_sym_DOLLARPBExportComments_DOLLAR,
    STATE(42), 1,
      sym_line_comment,
    ACTIONS(160), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [921] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      sym_close_parenthesis,
    STATE(43), 1,
      sym_line_comment,
    STATE(45), 1,
      aux_sym_datawindow_map_list_repeat1,
  [940] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(169), 1,
      sym_close_parenthesis,
    STATE(44), 2,
      sym_line_comment,
      aux_sym_datawindow_property_assignment_repeat1,
  [957] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(171), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      sym_close_parenthesis,
    STATE(45), 2,
      sym_line_comment,
      aux_sym_datawindow_map_list_repeat1,
  [974] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(46), 1,
      sym_line_comment,
    ACTIONS(176), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [988] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(47), 1,
      sym_line_comment,
    ACTIONS(96), 2,
      sym_identifier,
      sym_close_parenthesis,
  [1002] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(78), 1,
      anon_sym_DOT,
    ACTIONS(104), 1,
      anon_sym_EQ,
    STATE(48), 1,
      sym_line_comment,
  [1018] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(49), 1,
      sym_line_comment,
    ACTIONS(178), 2,
      sym_identifier,
      sym_close_parenthesis,
  [1032] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(50), 1,
      sym_line_comment,
    ACTIONS(180), 2,
      sym_identifier,
      sym_close_parenthesis,
  [1046] = 5,
    ACTIONS(110), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      sym_block_comment,
    ACTIONS(182), 1,
      aux_sym_string_literal_token2,
    ACTIONS(184), 1,
      sym_single_quote,
    STATE(51), 1,
      sym_line_comment,
  [1062] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(52), 1,
      sym_line_comment,
    ACTIONS(186), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [1076] = 5,
    ACTIONS(110), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      sym_block_comment,
    ACTIONS(188), 1,
      aux_sym_string_literal_token1,
    ACTIONS(190), 1,
      sym_double_quote,
    STATE(53), 1,
      sym_line_comment,
  [1092] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(54), 1,
      sym_line_comment,
    ACTIONS(192), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1106] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(55), 1,
      sym_line_comment,
    ACTIONS(194), 2,
      sym_identifier,
      sym_close_parenthesis,
  [1120] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(37), 1,
      sym_open_parenthesis,
    STATE(56), 1,
      sym_line_comment,
    STATE(62), 1,
      sym_datawindow_map_list,
  [1136] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(57), 1,
      sym_line_comment,
    ACTIONS(196), 2,
      sym_identifier,
      sym_close_parenthesis,
  [1150] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(58), 1,
      sym_line_comment,
    ACTIONS(198), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1164] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(59), 1,
      sym_line_comment,
    ACTIONS(200), 2,
      aux_sym_release_statement_token1,
      sym_identifier,
  [1178] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(202), 1,
      sym_integer_literal,
    ACTIONS(204), 1,
      sym_decimal_literal,
    STATE(60), 1,
      sym_line_comment,
  [1194] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(78), 1,
      anon_sym_DOT,
    ACTIONS(106), 1,
      sym_open_parenthesis,
    STATE(61), 1,
      sym_line_comment,
  [1210] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(62), 1,
      sym_line_comment,
    ACTIONS(169), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1224] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(63), 1,
      sym_line_comment,
    ACTIONS(206), 2,
      sym_identifier,
      sym_close_parenthesis,
  [1238] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(208), 1,
      anon_sym_srd,
    STATE(42), 1,
      sym_file_extension,
    STATE(64), 1,
      sym_line_comment,
  [1254] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(65), 1,
      sym_line_comment,
    ACTIONS(210), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1268] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(66), 1,
      sym_line_comment,
    ACTIONS(174), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1282] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(67), 1,
      sym_line_comment,
    ACTIONS(212), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1296] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(214), 1,
      sym_identifier,
    STATE(29), 1,
      sym_export_header_identifier_content,
    STATE(68), 1,
      sym_line_comment,
  [1312] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(69), 1,
      sym_line_comment,
    ACTIONS(216), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1326] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(78), 1,
      anon_sym_DOT,
    STATE(70), 1,
      sym_line_comment,
  [1339] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(218), 1,
      sym_close_parenthesis,
    STATE(71), 1,
      sym_line_comment,
  [1352] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(220), 1,
      anon_sym_SEMI,
    STATE(72), 1,
      sym_line_comment,
  [1365] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(222), 1,
      sym_close_parenthesis,
    STATE(73), 1,
      sym_line_comment,
  [1378] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(224), 1,
      anon_sym_DOT,
    STATE(74), 1,
      sym_line_comment,
  [1391] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
    STATE(75), 1,
      sym_line_comment,
  [1404] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(228), 1,
      ts_builtin_sym_end,
    STATE(76), 1,
      sym_line_comment,
  [1417] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(230), 1,
      sym_identifier,
    STATE(77), 1,
      sym_line_comment,
  [1430] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(128), 1,
      sym_close_parenthesis,
    STATE(78), 1,
      sym_line_comment,
  [1443] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(232), 1,
      ts_builtin_sym_end,
    STATE(79), 1,
      sym_line_comment,
  [1456] = 4,
    ACTIONS(110), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      sym_block_comment,
    ACTIONS(234), 1,
      aux_sym_line_comment_token1,
    STATE(80), 1,
      sym_line_comment,
  [1469] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(236), 1,
      sym_close_parenthesis,
    STATE(81), 1,
      sym_line_comment,
  [1482] = 4,
    ACTIONS(110), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(112), 1,
      sym_block_comment,
    ACTIONS(238), 1,
      aux_sym_export_header_comments_token1,
    STATE(82), 1,
      sym_line_comment,
  [1495] = 1,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 159,
  [SMALL_STATE(7)] = 196,
  [SMALL_STATE(8)] = 226,
  [SMALL_STATE(9)] = 258,
  [SMALL_STATE(10)] = 290,
  [SMALL_STATE(11)] = 321,
  [SMALL_STATE(12)] = 352,
  [SMALL_STATE(13)] = 378,
  [SMALL_STATE(14)] = 406,
  [SMALL_STATE(15)] = 424,
  [SMALL_STATE(16)] = 442,
  [SMALL_STATE(17)] = 462,
  [SMALL_STATE(18)] = 482,
  [SMALL_STATE(19)] = 500,
  [SMALL_STATE(20)] = 518,
  [SMALL_STATE(21)] = 535,
  [SMALL_STATE(22)] = 552,
  [SMALL_STATE(23)] = 569,
  [SMALL_STATE(24)] = 584,
  [SMALL_STATE(25)] = 599,
  [SMALL_STATE(26)] = 618,
  [SMALL_STATE(27)] = 637,
  [SMALL_STATE(28)] = 656,
  [SMALL_STATE(29)] = 673,
  [SMALL_STATE(30)] = 690,
  [SMALL_STATE(31)] = 709,
  [SMALL_STATE(32)] = 724,
  [SMALL_STATE(33)] = 743,
  [SMALL_STATE(34)] = 762,
  [SMALL_STATE(35)] = 781,
  [SMALL_STATE(36)] = 800,
  [SMALL_STATE(37)] = 819,
  [SMALL_STATE(38)] = 834,
  [SMALL_STATE(39)] = 851,
  [SMALL_STATE(40)] = 868,
  [SMALL_STATE(41)] = 885,
  [SMALL_STATE(42)] = 904,
  [SMALL_STATE(43)] = 921,
  [SMALL_STATE(44)] = 940,
  [SMALL_STATE(45)] = 957,
  [SMALL_STATE(46)] = 974,
  [SMALL_STATE(47)] = 988,
  [SMALL_STATE(48)] = 1002,
  [SMALL_STATE(49)] = 1018,
  [SMALL_STATE(50)] = 1032,
  [SMALL_STATE(51)] = 1046,
  [SMALL_STATE(52)] = 1062,
  [SMALL_STATE(53)] = 1076,
  [SMALL_STATE(54)] = 1092,
  [SMALL_STATE(55)] = 1106,
  [SMALL_STATE(56)] = 1120,
  [SMALL_STATE(57)] = 1136,
  [SMALL_STATE(58)] = 1150,
  [SMALL_STATE(59)] = 1164,
  [SMALL_STATE(60)] = 1178,
  [SMALL_STATE(61)] = 1194,
  [SMALL_STATE(62)] = 1210,
  [SMALL_STATE(63)] = 1224,
  [SMALL_STATE(64)] = 1238,
  [SMALL_STATE(65)] = 1254,
  [SMALL_STATE(66)] = 1268,
  [SMALL_STATE(67)] = 1282,
  [SMALL_STATE(68)] = 1296,
  [SMALL_STATE(69)] = 1312,
  [SMALL_STATE(70)] = 1326,
  [SMALL_STATE(71)] = 1339,
  [SMALL_STATE(72)] = 1352,
  [SMALL_STATE(73)] = 1365,
  [SMALL_STATE(74)] = 1378,
  [SMALL_STATE(75)] = 1391,
  [SMALL_STATE(76)] = 1404,
  [SMALL_STATE(77)] = 1417,
  [SMALL_STATE(78)] = 1430,
  [SMALL_STATE(79)] = 1443,
  [SMALL_STATE(80)] = 1456,
  [SMALL_STATE(81)] = 1469,
  [SMALL_STATE(82)] = 1482,
  [SMALL_STATE(83)] = 1495,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_file_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_datawindow_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_datawindow_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_file, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_datawindow_property_list_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_property_list_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_list, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_method_invocation, 5, 0, 5),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_datawindow_method_invocation, 5, 0, 5),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_method_invocation, 6, 0, 5),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_datawindow_method_invocation, 6, 0, 5),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_header, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_statement, 1, 0, 1),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_datawindow_statement, 1, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_method_invocation, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_datawindow_method_invocation, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_method_invocation, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_datawindow_method_invocation, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_release_statement, 3, 0, 2),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_release_statement, 3, 0, 2),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_field_access, 3, 0, 3),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_assignment, 3, 0, 6),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_file_repeat1, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_datawindow_file_repeat1, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_header_identifier, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_header_identifier, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 8),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(51),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat2, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_extension, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_extension, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_header_identifier_content, 3, 0, 4),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_header_identifier_content, 3, 0, 4),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_datawindow_property_assignment_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_property_assignment_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_datawindow_map_list_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_map_list_repeat1, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_map_list, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_assignment, 4, 0, 7),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_property_list_repeat1, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat2, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat2, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_header_comments, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_map_list, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_assignment, 5, 0, 7),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_assignment, 6, 0, 6),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_map_list, 3, 0, 9),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_header, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_assignment, 6, 0, 7),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_map_list_repeat1, 2, 0, 9),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_map_list, 4, 0, 9),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_map_list, 4, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [226] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_datawindow(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "datawindow",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
