/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 6
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_release_statement_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_DOT = 4,
  anon_sym_EQ = 5,
  anon_sym_COMMA = 6,
  aux_sym_export_header_identifier_token1 = 7,
  anon_sym_DOLLARPBExportComments_DOLLAR = 8,
  aux_sym_export_header_comments_token1 = 9,
  anon_sym_srd = 10,
  sym_integer_literal = 11,
  sym_decimal_literal = 12,
  sym_real_literal = 13,
  sym_date_literal = 14,
  sym_time_literal = 15,
  aux_sym_string_literal_token1 = 16,
  aux_sym_string_literal_token2 = 17,
  aux_sym_boolean_literal_token1 = 18,
  aux_sym_boolean_literal_token2 = 19,
  anon_sym_SLASH_SLASH = 20,
  aux_sym_line_comment_token1 = 21,
  sym_block_comment = 22,
  sym_open_parenthesis = 23,
  sym_close_parenthesis = 24,
  sym_single_quote = 25,
  sym_double_quote = 26,
  sym_source_file = 27,
  sym_datawindow_file = 28,
  sym_release_statement = 29,
  sym_datawindow_statement = 30,
  sym_datawindow_method_invocation = 31,
  sym_datawindow_field_access = 32,
  sym_datawindow_property_list = 33,
  sym_datawindow_property_assignment = 34,
  sym_datawindow_map_list = 35,
  sym_export_header = 36,
  sym_export_header_identifier = 37,
  sym_export_header_identifier_content = 38,
  sym_export_header_comments = 39,
  sym_file_extension = 40,
  sym__literal = 41,
  sym_string_literal = 42,
  sym_boolean_literal = 43,
  sym_line_comment = 44,
  aux_sym_datawindow_file_repeat1 = 45,
  aux_sym_datawindow_property_list_repeat1 = 46,
  aux_sym_datawindow_property_assignment_repeat1 = 47,
  aux_sym_datawindow_map_list_repeat1 = 48,
  aux_sym_string_literal_repeat1 = 49,
  aux_sym_string_literal_repeat2 = 50,
  alias_sym_field = 51,
  alias_sym_file_name = 52,
  alias_sym_object = 53,
  alias_sym_release_version = 54,
  alias_sym_string_content = 55,
  alias_sym_value = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "method",
  [aux_sym_release_statement_token1] = "release",
  [anon_sym_SEMI] = ";",
  [anon_sym_DOT] = ".",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [aux_sym_export_header_identifier_token1] = "export_header_identifier_text",
  [anon_sym_DOLLARPBExportComments_DOLLAR] = "export_header_comments_text",
  [aux_sym_export_header_comments_token1] = "export_header_comments_content",
  [anon_sym_srd] = "dataobject_file_extension",
  [sym_integer_literal] = "integer_literal",
  [sym_decimal_literal] = "decimal_literal",
  [sym_real_literal] = "real_literal",
  [sym_date_literal] = "date_literal",
  [sym_time_literal] = "time_literal",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [aux_sym_boolean_literal_token1] = "true",
  [aux_sym_boolean_literal_token2] = "false",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [sym_block_comment] = "block_comment",
  [sym_open_parenthesis] = "open_parenthesis",
  [sym_close_parenthesis] = "close_parenthesis",
  [sym_single_quote] = "single_quote",
  [sym_double_quote] = "double_quote",
  [sym_source_file] = "source_file",
  [sym_datawindow_file] = "datawindow_file",
  [sym_release_statement] = "release_statement",
  [sym_datawindow_statement] = "datawindow_statement",
  [sym_datawindow_method_invocation] = "datawindow_method_invocation",
  [sym_datawindow_field_access] = "property",
  [sym_datawindow_property_list] = "datawindow_property_list",
  [sym_datawindow_property_assignment] = "datawindow_property_assignment",
  [sym_datawindow_map_list] = "datawindow_map_list",
  [sym_export_header] = "export_header",
  [sym_export_header_identifier] = "export_header_identifier",
  [sym_export_header_identifier_content] = "export_header_identifier_content",
  [sym_export_header_comments] = "export_header_comments",
  [sym_file_extension] = "file_extension",
  [sym__literal] = "_literal",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_line_comment] = "line_comment",
  [aux_sym_datawindow_file_repeat1] = "datawindow_file_repeat1",
  [aux_sym_datawindow_property_list_repeat1] = "datawindow_property_list_repeat1",
  [aux_sym_datawindow_property_assignment_repeat1] = "datawindow_property_assignment_repeat1",
  [aux_sym_datawindow_map_list_repeat1] = "datawindow_map_list_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_string_literal_repeat2] = "string_literal_repeat2",
  [alias_sym_field] = "field",
  [alias_sym_file_name] = "file_name",
  [alias_sym_object] = "object",
  [alias_sym_release_version] = "release_version",
  [alias_sym_string_content] = "string_content",
  [alias_sym_value] = "value",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_release_statement_token1] = aux_sym_release_statement_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_export_header_identifier_token1] = aux_sym_export_header_identifier_token1,
  [anon_sym_DOLLARPBExportComments_DOLLAR] = anon_sym_DOLLARPBExportComments_DOLLAR,
  [aux_sym_export_header_comments_token1] = aux_sym_export_header_comments_token1,
  [anon_sym_srd] = anon_sym_srd,
  [sym_integer_literal] = sym_integer_literal,
  [sym_decimal_literal] = sym_decimal_literal,
  [sym_real_literal] = sym_real_literal,
  [sym_date_literal] = sym_date_literal,
  [sym_time_literal] = sym_time_literal,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [aux_sym_boolean_literal_token1] = aux_sym_boolean_literal_token1,
  [aux_sym_boolean_literal_token2] = aux_sym_boolean_literal_token2,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [sym_block_comment] = sym_block_comment,
  [sym_open_parenthesis] = sym_open_parenthesis,
  [sym_close_parenthesis] = sym_close_parenthesis,
  [sym_single_quote] = sym_single_quote,
  [sym_double_quote] = sym_double_quote,
  [sym_source_file] = sym_source_file,
  [sym_datawindow_file] = sym_datawindow_file,
  [sym_release_statement] = sym_release_statement,
  [sym_datawindow_statement] = sym_datawindow_statement,
  [sym_datawindow_method_invocation] = sym_datawindow_method_invocation,
  [sym_datawindow_field_access] = sym_datawindow_field_access,
  [sym_datawindow_property_list] = sym_datawindow_property_list,
  [sym_datawindow_property_assignment] = sym_datawindow_property_assignment,
  [sym_datawindow_map_list] = sym_datawindow_map_list,
  [sym_export_header] = sym_export_header,
  [sym_export_header_identifier] = sym_export_header_identifier,
  [sym_export_header_identifier_content] = sym_export_header_identifier_content,
  [sym_export_header_comments] = sym_export_header_comments,
  [sym_file_extension] = sym_file_extension,
  [sym__literal] = sym__literal,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_line_comment] = sym_line_comment,
  [aux_sym_datawindow_file_repeat1] = aux_sym_datawindow_file_repeat1,
  [aux_sym_datawindow_property_list_repeat1] = aux_sym_datawindow_property_list_repeat1,
  [aux_sym_datawindow_property_assignment_repeat1] = aux_sym_datawindow_property_assignment_repeat1,
  [aux_sym_datawindow_map_list_repeat1] = aux_sym_datawindow_map_list_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_string_literal_repeat2] = aux_sym_string_literal_repeat2,
  [alias_sym_field] = alias_sym_field,
  [alias_sym_file_name] = alias_sym_file_name,
  [alias_sym_object] = alias_sym_object,
  [alias_sym_release_version] = alias_sym_release_version,
  [alias_sym_string_content] = alias_sym_string_content,
  [alias_sym_value] = alias_sym_value,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_release_statement_token1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_export_header_identifier_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLARPBExportComments_DOLLAR] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_export_header_comments_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_srd] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_real_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_date_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_time_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_boolean_literal_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_boolean_literal_token2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_open_parenthesis] = {
    .visible = true,
    .named = true,
  },
  [sym_close_parenthesis] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_file] = {
    .visible = true,
    .named = true,
  },
  [sym_release_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_method_invocation] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_field_access] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_property_list] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_property_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_datawindow_map_list] = {
    .visible = true,
    .named = true,
  },
  [sym_export_header] = {
    .visible = true,
    .named = true,
  },
  [sym_export_header_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_export_header_identifier_content] = {
    .visible = true,
    .named = true,
  },
  [sym_export_header_comments] = {
    .visible = true,
    .named = true,
  },
  [sym_file_extension] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_datawindow_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_datawindow_property_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_datawindow_property_assignment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_datawindow_map_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat2] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_field] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_file_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_object] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_release_version] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_value] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_release_version,
  },
  [2] = {
    [0] = alias_sym_file_name,
  },
  [3] = {
    [0] = alias_sym_object,
    [2] = alias_sym_field,
  },
  [4] = {
    [0] = alias_sym_object,
    [1] = alias_sym_object,
  },
  [5] = {
    [0] = sym_datawindow_field_access,
    [2] = alias_sym_value,
  },
  [6] = {
    [0] = sym_datawindow_field_access,
  },
  [7] = {
    [1] = alias_sym_string_content,
  },
  [8] = {
    [1] = alias_sym_value,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_datawindow_method_invocation, 2,
    sym_datawindow_method_invocation,
    alias_sym_object,
  sym_datawindow_field_access, 2,
    sym_datawindow_field_access,
    alias_sym_object,
  sym__literal, 2,
    sym__literal,
    alias_sym_value,
  aux_sym_string_literal_repeat1, 2,
    aux_sym_string_literal_repeat1,
    alias_sym_string_content,
  aux_sym_string_literal_repeat2, 2,
    aux_sym_string_literal_repeat2,
    alias_sym_string_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(75);
      ADVANCE_MAP(
        '"', 158,
        '$', 20,
        '\'', 157,
        '(', 155,
        ')', 156,
        ',', 82,
        '.', 80,
        '/', 7,
        '2', 123,
        ';', 78,
        '=', 81,
        'H', 93,
        'F', 108,
        'f', 108,
        'R', 113,
        'r', 113,
        'T', 116,
        't', 116,
        '0', 124,
        '1', 124,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(127);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 158,
        '$', 20,
        '\'', 157,
        '.', 61,
        '/', 7,
        '2', 123,
        'H', 13,
        'F', 45,
        'f', 45,
        'R', 52,
        'r', 52,
        'T', 55,
        't', 55,
        '0', 124,
        '1', 124,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(158);
      if (lookahead == '/') ADVANCE(141);
      if (lookahead == '\\') ADVANCE(71);
      if (lookahead == '~') ADVANCE(142);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(141);
      if (lookahead != 0) ADVANCE(141);
      END_STATE();
    case 3:
      if (lookahead == '$') ADVANCE(83);
      END_STATE();
    case 4:
      if (lookahead == '$') ADVANCE(85);
      END_STATE();
    case 5:
      if (lookahead == '$') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(157);
      if (lookahead == '/') ADVANCE(143);
      if (lookahead == '\\') ADVANCE(72);
      if (lookahead == '~') ADVANCE(144);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(143);
      if (lookahead != 0) ADVANCE(143);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(147);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(154);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(70);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(68);
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(60);
      END_STATE();
    case 13:
      if (lookahead == 'A') ADVANCE(5);
      END_STATE();
    case 14:
      if (lookahead == 'B') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'B') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'C') ADVANCE(31);
      if (lookahead == 'H') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(42);
      END_STATE();
    case 18:
      if (lookahead == 'E') ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == 'H') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'P') ADVANCE(14);
      END_STATE();
    case 21:
      if (lookahead == 'P') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 28:
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(30);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(3);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 38:
      if (lookahead == 's') ADVANCE(4);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 42:
      if (lookahead == 'x') ADVANCE(33);
      END_STATE();
    case 43:
      if (lookahead == 'x') ADVANCE(34);
      END_STATE();
    case 44:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      END_STATE();
    case 45:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 46:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(57);
      END_STATE();
    case 47:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      END_STATE();
    case 48:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(145);
      END_STATE();
    case 49:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(146);
      END_STATE();
    case 50:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 51:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 52:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 53:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 54:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 55:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 56:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(49);
      END_STATE();
    case 57:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(50);
      END_STATE();
    case 58:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(48);
      END_STATE();
    case 59:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(63);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(65);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      END_STATE();
    case 62:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      END_STATE();
    case 63:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 64:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 65:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      END_STATE();
    case 66:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      END_STATE();
    case 67:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 68:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 69:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 71:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(141);
      END_STATE();
    case 72:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(143);
      END_STATE();
    case 73:
      if (eof) ADVANCE(75);
      ADVANCE_MAP(
        '"', 158,
        '\'', 157,
        '(', 155,
        ')', 156,
        ',', 82,
        '.', 61,
        '/', 7,
        '2', 123,
        'F', 108,
        'f', 108,
        'T', 116,
        't', 116,
        '0', 124,
        '1', 124,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(73);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(127);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 74:
      if (eof) ADVANCE(75);
      if (lookahead == '(') ADVANCE(155);
      if (lookahead == '.') ADVANCE(79);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_release_statement_token1);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_release_statement_token1);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_export_header_identifier_token1);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_export_header_identifier_token1);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_DOLLARPBExportComments_DOLLAR);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_export_header_comments_token1);
      if (lookahead == '*') ADVANCE(88);
      if (lookahead == '/') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(90);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_export_header_comments_token1);
      if (lookahead == '*') ADVANCE(87);
      if (lookahead == '/') ADVANCE(90);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(9);
      if (lookahead != 0) ADVANCE(88);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_export_header_comments_token1);
      if (lookahead == '*') ADVANCE(87);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(9);
      if (lookahead != 0) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_export_header_comments_token1);
      if (lookahead == '/') ADVANCE(86);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_export_header_comments_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$') ADVANCE(97);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$') ADVANCE(84);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(91);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'B') ADVANCE(95);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E') ADVANCE(107);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'H') ADVANCE(100);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P') ADVANCE(94);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(99);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(101);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(98);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(105);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(104);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(102);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(106);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(92);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(96);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(103);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(114);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(118);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(120);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(77);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(109);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(115);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(117);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(112);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(119);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(110);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(111);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(110);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (('#' <= lookahead && lookahead <= '%') ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '-') ADVANCE(69);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == ':') ADVANCE(59);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(122);
      if (('4' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_decimal_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_decimal_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_real_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_date_literal);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_time_literal);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_time_literal);
      if (lookahead == '.') ADVANCE(66);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_time_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_time_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_time_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_time_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_time_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(139);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '"') ADVANCE(141);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead == '\'') ADVANCE(143);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(aux_sym_boolean_literal_token1);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(aux_sym_boolean_literal_token2);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(90);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(151);
      if (lookahead == '/') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(150);
      if (lookahead == '/') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(151);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(151);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '/') ADVANCE(149);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(152);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(153);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_open_parenthesis);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_close_parenthesis);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_single_quote);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_double_quote);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 's') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == 'd') ADVANCE(3);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_srd);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 73},
  [3] = {.lex_state = 73},
  [4] = {.lex_state = 73},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 73},
  [7] = {.lex_state = 73},
  [8] = {.lex_state = 73},
  [9] = {.lex_state = 73},
  [10] = {.lex_state = 73},
  [11] = {.lex_state = 73},
  [12] = {.lex_state = 73},
  [13] = {.lex_state = 73},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 74},
  [17] = {.lex_state = 74},
  [18] = {.lex_state = 74},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 74},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 74},
  [23] = {.lex_state = 73},
  [24] = {.lex_state = 73},
  [25] = {.lex_state = 73},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 74},
  [29] = {.lex_state = 74},
  [30] = {.lex_state = 73},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 73},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 11},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 73},
  [45] = {.lex_state = 73},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 73},
  [48] = {.lex_state = 73},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 73},
  [52] = {.lex_state = 73},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 73},
  [55] = {.lex_state = 74},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 74},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 73},
  [62] = {.lex_state = 73},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 89},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 73},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 74},
  [75] = {.lex_state = 73},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 152},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 74},
  [84] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_release_statement_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_export_header_identifier_token1] = ACTIONS(1),
    [anon_sym_DOLLARPBExportComments_DOLLAR] = ACTIONS(1),
    [anon_sym_srd] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_decimal_literal] = ACTIONS(1),
    [sym_real_literal] = ACTIONS(1),
    [sym_date_literal] = ACTIONS(1),
    [sym_time_literal] = ACTIONS(1),
    [aux_sym_boolean_literal_token1] = ACTIONS(1),
    [aux_sym_boolean_literal_token2] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [sym_open_parenthesis] = ACTIONS(1),
    [sym_close_parenthesis] = ACTIONS(1),
    [sym_single_quote] = ACTIONS(1),
    [sym_double_quote] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(80),
    [sym_datawindow_file] = STATE(79),
    [sym_release_statement] = STATE(13),
    [sym_export_header] = STATE(19),
    [sym_export_header_identifier] = STATE(21),
    [sym_line_comment] = STATE(1),
    [aux_sym_release_statement_token1] = ACTIONS(7),
    [aux_sym_export_header_identifier_token1] = ACTIONS(9),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_close_parenthesis,
    ACTIONS(21), 1,
      sym_single_quote,
    ACTIONS(23), 1,
      sym_double_quote,
    STATE(2), 1,
      sym_line_comment,
    STATE(34), 1,
      sym__literal,
    ACTIONS(13), 2,
      sym_integer_literal,
      sym_decimal_literal,
    ACTIONS(17), 2,
      aux_sym_boolean_literal_token1,
      aux_sym_boolean_literal_token2,
    STATE(24), 2,
      sym_string_literal,
      sym_boolean_literal,
    ACTIONS(15), 3,
      sym_real_literal,
      sym_date_literal,
      sym_time_literal,
  [42] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(21), 1,
      sym_single_quote,
    ACTIONS(23), 1,
      sym_double_quote,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(27), 1,
      sym_open_parenthesis,
    STATE(3), 1,
      sym_line_comment,
    STATE(47), 1,
      sym__literal,
    ACTIONS(13), 2,
      sym_integer_literal,
      sym_decimal_literal,
    ACTIONS(17), 2,
      aux_sym_boolean_literal_token1,
      aux_sym_boolean_literal_token2,
    STATE(24), 2,
      sym_string_literal,
      sym_boolean_literal,
    ACTIONS(15), 3,
      sym_real_literal,
      sym_date_literal,
      sym_time_literal,
  [84] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(21), 1,
      sym_single_quote,
    ACTIONS(23), 1,
      sym_double_quote,
    ACTIONS(29), 1,
      sym_identifier,
    STATE(4), 1,
      sym_line_comment,
    STATE(64), 1,
      sym__literal,
    ACTIONS(13), 2,
      sym_integer_literal,
      sym_decimal_literal,
    ACTIONS(17), 2,
      aux_sym_boolean_literal_token1,
      aux_sym_boolean_literal_token2,
    STATE(24), 2,
      sym_string_literal,
      sym_boolean_literal,
    ACTIONS(15), 3,
      sym_real_literal,
      sym_date_literal,
      sym_time_literal,
  [123] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(21), 1,
      sym_single_quote,
    ACTIONS(23), 1,
      sym_double_quote,
    STATE(5), 1,
      sym_line_comment,
    STATE(77), 1,
      sym__literal,
    ACTIONS(13), 2,
      sym_integer_literal,
      sym_decimal_literal,
    ACTIONS(31), 2,
      aux_sym_boolean_literal_token1,
      aux_sym_boolean_literal_token2,
    STATE(24), 2,
      sym_string_literal,
      sym_boolean_literal,
    ACTIONS(15), 3,
      sym_real_literal,
      sym_date_literal,
      sym_time_literal,
  [159] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      sym_open_parenthesis,
    ACTIONS(37), 1,
      sym_close_parenthesis,
    STATE(6), 1,
      sym_line_comment,
    STATE(11), 1,
      aux_sym_datawindow_property_list_repeat1,
    STATE(41), 1,
      sym_datawindow_map_list,
    STATE(57), 1,
      sym_datawindow_field_access,
    STATE(62), 1,
      sym_datawindow_property_assignment,
    STATE(68), 1,
      sym_datawindow_property_list,
    STATE(74), 1,
      sym_datawindow_method_invocation,
  [196] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(39), 1,
      sym_close_parenthesis,
    STATE(7), 1,
      sym_line_comment,
    STATE(11), 1,
      aux_sym_datawindow_property_list_repeat1,
    STATE(57), 1,
      sym_datawindow_field_access,
    STATE(62), 1,
      sym_datawindow_property_assignment,
    STATE(73), 1,
      sym_datawindow_property_list,
    STATE(74), 1,
      sym_datawindow_method_invocation,
  [227] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(41), 1,
      sym_close_parenthesis,
    STATE(8), 1,
      sym_line_comment,
    STATE(11), 1,
      aux_sym_datawindow_property_list_repeat1,
    STATE(57), 1,
      sym_datawindow_field_access,
    STATE(62), 1,
      sym_datawindow_property_assignment,
    STATE(74), 1,
      sym_datawindow_method_invocation,
    STATE(78), 1,
      sym_datawindow_property_list,
  [258] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      sym_identifier,
    STATE(29), 1,
      sym_datawindow_method_invocation,
    STATE(52), 1,
      sym_datawindow_statement,
    STATE(74), 1,
      sym_datawindow_field_access,
    STATE(9), 2,
      sym_line_comment,
      aux_sym_datawindow_file_repeat1,
  [284] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(9), 1,
      aux_sym_datawindow_file_repeat1,
    STATE(10), 1,
      sym_line_comment,
    STATE(29), 1,
      sym_datawindow_method_invocation,
    STATE(52), 1,
      sym_datawindow_statement,
    STATE(74), 1,
      sym_datawindow_field_access,
  [312] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(52), 1,
      sym_close_parenthesis,
    STATE(11), 1,
      sym_line_comment,
    STATE(12), 1,
      aux_sym_datawindow_property_list_repeat1,
    STATE(57), 1,
      sym_datawindow_field_access,
    STATE(62), 1,
      sym_datawindow_property_assignment,
    STATE(74), 1,
      sym_datawindow_method_invocation,
  [340] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(54), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_close_parenthesis,
    STATE(57), 1,
      sym_datawindow_field_access,
    STATE(62), 1,
      sym_datawindow_property_assignment,
    STATE(74), 1,
      sym_datawindow_method_invocation,
    STATE(12), 2,
      sym_line_comment,
      aux_sym_datawindow_property_list_repeat1,
  [366] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(10), 1,
      aux_sym_datawindow_file_repeat1,
    STATE(13), 1,
      sym_line_comment,
    STATE(29), 1,
      sym_datawindow_method_invocation,
    STATE(52), 1,
      sym_datawindow_statement,
    STATE(74), 1,
      sym_datawindow_field_access,
  [391] = 5,
    ACTIONS(59), 1,
      aux_sym_string_literal_token1,
    ACTIONS(62), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_block_comment,
    ACTIONS(66), 1,
      sym_double_quote,
    STATE(14), 2,
      sym_line_comment,
      aux_sym_string_literal_repeat1,
  [408] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    ACTIONS(71), 1,
      sym_close_parenthesis,
    STATE(15), 2,
      sym_line_comment,
      aux_sym_datawindow_map_list_repeat1,
  [425] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_open_parenthesis,
    STATE(16), 1,
      sym_line_comment,
    ACTIONS(73), 2,
      anon_sym_DOT,
      anon_sym_EQ,
  [442] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(77), 1,
      anon_sym_DOT,
    ACTIONS(79), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      sym_open_parenthesis,
    STATE(17), 1,
      sym_line_comment,
  [461] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(18), 1,
      sym_line_comment,
    ACTIONS(83), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_identifier,
  [476] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(7), 1,
      aux_sym_release_statement_token1,
    STATE(13), 1,
      sym_release_statement,
    STATE(19), 1,
      sym_line_comment,
    STATE(76), 1,
      sym_datawindow_file,
  [495] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(20), 1,
      sym_line_comment,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_identifier,
  [510] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(87), 1,
      aux_sym_release_statement_token1,
    ACTIONS(89), 1,
      anon_sym_DOLLARPBExportComments_DOLLAR,
    STATE(21), 1,
      sym_line_comment,
    STATE(71), 1,
      sym_export_header_comments,
  [529] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(22), 1,
      sym_line_comment,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_identifier,
  [544] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(95), 1,
      sym_open_parenthesis,
    STATE(23), 1,
      sym_line_comment,
    ACTIONS(93), 2,
      sym_identifier,
      sym_close_parenthesis,
  [561] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(24), 1,
      sym_line_comment,
    ACTIONS(97), 3,
      anon_sym_COMMA,
      sym_identifier,
      sym_close_parenthesis,
  [576] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(25), 1,
      sym_line_comment,
    ACTIONS(99), 3,
      anon_sym_COMMA,
      sym_identifier,
      sym_close_parenthesis,
  [591] = 6,
    ACTIONS(62), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_block_comment,
    ACTIONS(101), 1,
      aux_sym_string_literal_token2,
    ACTIONS(103), 1,
      sym_single_quote,
    STATE(26), 1,
      sym_line_comment,
    STATE(31), 1,
      aux_sym_string_literal_repeat2,
  [610] = 6,
    ACTIONS(62), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_block_comment,
    ACTIONS(103), 1,
      sym_double_quote,
    ACTIONS(105), 1,
      aux_sym_string_literal_token1,
    STATE(27), 1,
      sym_line_comment,
    STATE(32), 1,
      aux_sym_string_literal_repeat1,
  [629] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(28), 1,
      sym_line_comment,
    ACTIONS(107), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_identifier,
  [644] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(77), 1,
      anon_sym_DOT,
    STATE(29), 1,
      sym_line_comment,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [661] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(30), 1,
      sym_line_comment,
    ACTIONS(111), 3,
      anon_sym_COMMA,
      sym_identifier,
      sym_close_parenthesis,
  [676] = 6,
    ACTIONS(62), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_block_comment,
    ACTIONS(101), 1,
      aux_sym_string_literal_token2,
    ACTIONS(113), 1,
      sym_single_quote,
    STATE(31), 1,
      sym_line_comment,
    STATE(37), 1,
      aux_sym_string_literal_repeat2,
  [695] = 6,
    ACTIONS(62), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_block_comment,
    ACTIONS(105), 1,
      aux_sym_string_literal_token1,
    ACTIONS(113), 1,
      sym_double_quote,
    STATE(14), 1,
      aux_sym_string_literal_repeat1,
    STATE(32), 1,
      sym_line_comment,
  [714] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    ACTIONS(117), 1,
      sym_close_parenthesis,
    STATE(33), 1,
      sym_line_comment,
    STATE(38), 1,
      aux_sym_datawindow_map_list_repeat1,
  [733] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    ACTIONS(119), 1,
      sym_close_parenthesis,
    STATE(34), 1,
      sym_line_comment,
    STATE(39), 1,
      aux_sym_datawindow_map_list_repeat1,
  [752] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    ACTIONS(123), 1,
      sym_close_parenthesis,
    STATE(35), 1,
      sym_line_comment,
    STATE(40), 1,
      aux_sym_datawindow_property_assignment_repeat1,
  [771] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(36), 1,
      sym_line_comment,
    ACTIONS(125), 3,
      anon_sym_COMMA,
      sym_identifier,
      sym_close_parenthesis,
  [786] = 5,
    ACTIONS(62), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_block_comment,
    ACTIONS(127), 1,
      aux_sym_string_literal_token2,
    ACTIONS(130), 1,
      sym_single_quote,
    STATE(37), 2,
      sym_line_comment,
      aux_sym_string_literal_repeat2,
  [803] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    ACTIONS(132), 1,
      sym_close_parenthesis,
    STATE(15), 1,
      aux_sym_datawindow_map_list_repeat1,
    STATE(38), 1,
      sym_line_comment,
  [822] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      sym_close_parenthesis,
    STATE(15), 1,
      aux_sym_datawindow_map_list_repeat1,
    STATE(39), 1,
      sym_line_comment,
  [841] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(139), 1,
      sym_close_parenthesis,
    STATE(40), 2,
      sym_line_comment,
      aux_sym_datawindow_property_assignment_repeat1,
  [858] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    ACTIONS(141), 1,
      sym_close_parenthesis,
    STATE(35), 1,
      aux_sym_datawindow_property_assignment_repeat1,
    STATE(41), 1,
      sym_line_comment,
  [877] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(143), 1,
      sym_integer_literal,
    ACTIONS(145), 1,
      sym_decimal_literal,
    STATE(42), 1,
      sym_line_comment,
  [893] = 5,
    ACTIONS(62), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_block_comment,
    ACTIONS(147), 1,
      aux_sym_string_literal_token1,
    ACTIONS(149), 1,
      sym_double_quote,
    STATE(43), 1,
      sym_line_comment,
  [909] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(151), 1,
      anon_sym_srd,
    STATE(44), 1,
      sym_line_comment,
    STATE(66), 1,
      sym_file_extension,
  [925] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(153), 1,
      sym_identifier,
    STATE(45), 1,
      sym_line_comment,
    STATE(53), 1,
      sym_export_header_identifier_content,
  [941] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(46), 1,
      sym_line_comment,
    ACTIONS(155), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [955] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(47), 1,
      sym_line_comment,
    ACTIONS(93), 2,
      sym_identifier,
      sym_close_parenthesis,
  [969] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(48), 1,
      sym_line_comment,
    ACTIONS(157), 2,
      sym_identifier,
      sym_close_parenthesis,
  [983] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(35), 1,
      sym_open_parenthesis,
    STATE(49), 1,
      sym_line_comment,
    STATE(60), 1,
      sym_datawindow_map_list,
  [999] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(50), 1,
      sym_line_comment,
    ACTIONS(159), 2,
      aux_sym_release_statement_token1,
      anon_sym_DOLLARPBExportComments_DOLLAR,
  [1013] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(51), 1,
      sym_line_comment,
    ACTIONS(161), 2,
      sym_identifier,
      sym_close_parenthesis,
  [1027] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(52), 1,
      sym_line_comment,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [1041] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(53), 1,
      sym_line_comment,
    ACTIONS(165), 2,
      aux_sym_release_statement_token1,
      anon_sym_DOLLARPBExportComments_DOLLAR,
  [1055] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(54), 1,
      sym_line_comment,
    ACTIONS(167), 2,
      sym_identifier,
      sym_close_parenthesis,
  [1069] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(77), 1,
      anon_sym_DOT,
    ACTIONS(81), 1,
      sym_open_parenthesis,
    STATE(55), 1,
      sym_line_comment,
  [1085] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(56), 1,
      sym_line_comment,
    ACTIONS(169), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1099] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(77), 1,
      anon_sym_DOT,
    ACTIONS(79), 1,
      anon_sym_EQ,
    STATE(57), 1,
      sym_line_comment,
  [1115] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(58), 1,
      sym_line_comment,
    ACTIONS(171), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1129] = 5,
    ACTIONS(62), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_block_comment,
    ACTIONS(173), 1,
      aux_sym_string_literal_token2,
    ACTIONS(175), 1,
      sym_single_quote,
    STATE(59), 1,
      sym_line_comment,
  [1145] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(60), 1,
      sym_line_comment,
    ACTIONS(139), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1159] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(61), 1,
      sym_line_comment,
    ACTIONS(177), 2,
      sym_identifier,
      sym_close_parenthesis,
  [1173] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(62), 1,
      sym_line_comment,
    ACTIONS(179), 2,
      sym_identifier,
      sym_close_parenthesis,
  [1187] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(63), 1,
      sym_line_comment,
    ACTIONS(181), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1201] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(64), 1,
      sym_line_comment,
    ACTIONS(71), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1215] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(65), 1,
      sym_line_comment,
    ACTIONS(183), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1229] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(66), 1,
      sym_line_comment,
    ACTIONS(185), 2,
      aux_sym_release_statement_token1,
      anon_sym_DOLLARPBExportComments_DOLLAR,
  [1243] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(67), 1,
      sym_line_comment,
    ACTIONS(187), 2,
      anon_sym_COMMA,
      sym_close_parenthesis,
  [1257] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(141), 1,
      sym_close_parenthesis,
    STATE(68), 1,
      sym_line_comment,
  [1270] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(189), 1,
      aux_sym_release_statement_token1,
    STATE(69), 1,
      sym_line_comment,
  [1283] = 4,
    ACTIONS(62), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_block_comment,
    ACTIONS(191), 1,
      aux_sym_export_header_comments_token1,
    STATE(70), 1,
      sym_line_comment,
  [1296] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(193), 1,
      aux_sym_release_statement_token1,
    STATE(71), 1,
      sym_line_comment,
  [1309] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(72), 1,
      sym_line_comment,
  [1322] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(197), 1,
      sym_close_parenthesis,
    STATE(73), 1,
      sym_line_comment,
  [1335] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(77), 1,
      anon_sym_DOT,
    STATE(74), 1,
      sym_line_comment,
  [1348] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(199), 1,
      sym_identifier,
    STATE(75), 1,
      sym_line_comment,
  [1361] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
    STATE(76), 1,
      sym_line_comment,
  [1374] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(203), 1,
      sym_close_parenthesis,
    STATE(77), 1,
      sym_line_comment,
  [1387] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(205), 1,
      sym_close_parenthesis,
    STATE(78), 1,
      sym_line_comment,
  [1400] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
    STATE(79), 1,
      sym_line_comment,
  [1413] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
    STATE(80), 1,
      sym_line_comment,
  [1426] = 4,
    ACTIONS(62), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(64), 1,
      sym_block_comment,
    ACTIONS(211), 1,
      aux_sym_line_comment_token1,
    STATE(81), 1,
      sym_line_comment,
  [1439] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(213), 1,
      anon_sym_SEMI,
    STATE(82), 1,
      sym_line_comment,
  [1452] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(215), 1,
      anon_sym_DOT,
    STATE(83), 1,
      sym_line_comment,
  [1465] = 1,
    ACTIONS(217), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 159,
  [SMALL_STATE(7)] = 196,
  [SMALL_STATE(8)] = 227,
  [SMALL_STATE(9)] = 258,
  [SMALL_STATE(10)] = 284,
  [SMALL_STATE(11)] = 312,
  [SMALL_STATE(12)] = 340,
  [SMALL_STATE(13)] = 366,
  [SMALL_STATE(14)] = 391,
  [SMALL_STATE(15)] = 408,
  [SMALL_STATE(16)] = 425,
  [SMALL_STATE(17)] = 442,
  [SMALL_STATE(18)] = 461,
  [SMALL_STATE(19)] = 476,
  [SMALL_STATE(20)] = 495,
  [SMALL_STATE(21)] = 510,
  [SMALL_STATE(22)] = 529,
  [SMALL_STATE(23)] = 544,
  [SMALL_STATE(24)] = 561,
  [SMALL_STATE(25)] = 576,
  [SMALL_STATE(26)] = 591,
  [SMALL_STATE(27)] = 610,
  [SMALL_STATE(28)] = 629,
  [SMALL_STATE(29)] = 644,
  [SMALL_STATE(30)] = 661,
  [SMALL_STATE(31)] = 676,
  [SMALL_STATE(32)] = 695,
  [SMALL_STATE(33)] = 714,
  [SMALL_STATE(34)] = 733,
  [SMALL_STATE(35)] = 752,
  [SMALL_STATE(36)] = 771,
  [SMALL_STATE(37)] = 786,
  [SMALL_STATE(38)] = 803,
  [SMALL_STATE(39)] = 822,
  [SMALL_STATE(40)] = 841,
  [SMALL_STATE(41)] = 858,
  [SMALL_STATE(42)] = 877,
  [SMALL_STATE(43)] = 893,
  [SMALL_STATE(44)] = 909,
  [SMALL_STATE(45)] = 925,
  [SMALL_STATE(46)] = 941,
  [SMALL_STATE(47)] = 955,
  [SMALL_STATE(48)] = 969,
  [SMALL_STATE(49)] = 983,
  [SMALL_STATE(50)] = 999,
  [SMALL_STATE(51)] = 1013,
  [SMALL_STATE(52)] = 1027,
  [SMALL_STATE(53)] = 1041,
  [SMALL_STATE(54)] = 1055,
  [SMALL_STATE(55)] = 1069,
  [SMALL_STATE(56)] = 1085,
  [SMALL_STATE(57)] = 1099,
  [SMALL_STATE(58)] = 1115,
  [SMALL_STATE(59)] = 1129,
  [SMALL_STATE(60)] = 1145,
  [SMALL_STATE(61)] = 1159,
  [SMALL_STATE(62)] = 1173,
  [SMALL_STATE(63)] = 1187,
  [SMALL_STATE(64)] = 1201,
  [SMALL_STATE(65)] = 1215,
  [SMALL_STATE(66)] = 1229,
  [SMALL_STATE(67)] = 1243,
  [SMALL_STATE(68)] = 1257,
  [SMALL_STATE(69)] = 1270,
  [SMALL_STATE(70)] = 1283,
  [SMALL_STATE(71)] = 1296,
  [SMALL_STATE(72)] = 1309,
  [SMALL_STATE(73)] = 1322,
  [SMALL_STATE(74)] = 1335,
  [SMALL_STATE(75)] = 1348,
  [SMALL_STATE(76)] = 1361,
  [SMALL_STATE(77)] = 1374,
  [SMALL_STATE(78)] = 1387,
  [SMALL_STATE(79)] = 1400,
  [SMALL_STATE(80)] = 1413,
  [SMALL_STATE(81)] = 1426,
  [SMALL_STATE(82)] = 1439,
  [SMALL_STATE(83)] = 1452,
  [SMALL_STATE(84)] = 1465,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_file_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_datawindow_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_file, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_list, 1, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_datawindow_property_list_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_property_list_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_datawindow_map_list_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_map_list_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_field_access, 3, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_method_invocation, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_method_invocation, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_header, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_method_invocation, 5, 0, 4),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_assignment, 3, 0, 5),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_method_invocation, 6, 0, 4),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_statement, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 7),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(59),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat2, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_datawindow_property_assignment_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_property_assignment_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_map_list, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_assignment, 5, 0, 6),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_extension, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_assignment, 4, 0, 6),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_file_repeat1, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_header_identifier, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_assignment, 6, 0, 5),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_map_list, 3, 0, 8),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_map_list, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat2, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat2, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_property_assignment, 6, 0, 6),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_property_list_repeat1, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_datawindow_map_list_repeat1, 2, 0, 8),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_map_list, 4, 0, 8),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_header_identifier_content, 3, 0, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_datawindow_map_list, 4, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_header_comments, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_header, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_release_statement, 3, 0, 1),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_datawindow(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "datawindow",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
